'use strict';
document.addEventListener('DOMContentLoaded',()=>{
 const G=window.PhonikaGames,{shuffle,arrangeTasks}=G,childTabs=document.getElementById('childTabs'),gamesTab=document.getElementById('gamesTab'),gamesGrid=document.getElementById('gamesGrid'),findGame=document.getElementById('findGame');
 const buildCard=G.gameCards.find(el=>el.textContent.includes('Собери слово'));if(buildCard)buildCard.id='buildWordGameCard';const buildGame=document.createElement('div');buildGame.id='buildWordGame';buildGame.className='find-game build-word-game';buildGame.hidden=true;buildGame.innerHTML='<div class="find-header"><button id="buildAllGames" class="find-back">← Игры</button><span class="find-title">Собери слово</span></div><div class="dino-track"><div class="dino-path"></div><div id="buildDinoSteps" class="dino-steps"></div><div id="buildDino" class="dino">🦕</div><div class="dino-finish">🏁</div></div><div class="build-task-row"><button id="buildPrev" class="find-nav-arrow">‹</button><div class="build-center"><button id="buildPicture" class="find-picture build-picture"></button><div id="buildSlots" class="build-slots"></div><div id="buildLetters" class="build-letters"></div></div><button id="buildNext" class="find-nav-arrow">›</button></div>';gamesGrid?.insertAdjacentElement('afterend',buildGame);
 const buildPicture=document.getElementById('buildPicture'),buildSlots=document.getElementById('buildSlots'),buildLetters=document.getElementById('buildLetters'),steps=document.getElementById('buildDinoSteps'),dino=document.getElementById('buildDino'),prev=document.getElementById('buildPrev'),next=document.getElementById('buildNext');let isOpen=false,index=0,session=[],original=[],completion=null;
 const pictureMap=()=>new Map(Object.values(curriculum).flat().map(([w,p])=>[w,p])),shuffled=(word,avoid=[])=>{const src=[...word.toUpperCase()],blocked=[src.join(''),...avoid];for(let i=0;i<8;i++){const c=shuffle(src);if(!blocked.includes(c.join('')))return c;}return [...src].reverse();};
 const reset=task=>{task.placedLetters=Array(task.shuffledLetters.length).fill(null);task.attempted=false;task.completed=false;task.hadWrongAttempt=false;return task;};
 const createSession=()=>{const words=[...new Set((sessionWords||[]).slice(0,wordSessionSize))],pics=pictureMap(),tasks=[];words.forEach(targetWord=>{const a=shuffled(targetWord),b=shuffled(targetWord,[a.join('')]);[a,b].forEach(ls=>{const tiles=ls.map((letter,id)=>({id,letter}));tasks.push({targetWord,picture:pics.get(targetWord)||'',shuffledLetters:tiles,placedLetters:Array(tiles.length).fill(null),attempted:false,completed:false,hadWrongAttempt:false,rewarded:false,closed:false});});});original=arrangeTasks(tasks);session=[...original];};
 const task=()=>session[index],progress=()=>original.filter(t=>t.rewarded).length,allClosed=()=>original.length>0&&progress()===original.length;const updateProgress=()=>{const p=progress(),goal=original.length;[...steps.children].forEach((s,i)=>{s.classList.toggle('done',i<p);s.innerHTML=i<p?'<span class="step-check">✓</span>':'';});const pct=goal?p/goal*100:0;dino.style.left=`calc(${pct}% - ${pct/100*46}px)`;};const makeProgress=()=>{steps.replaceChildren();for(let i=0;i<original.length;i++){const s=document.createElement('span');s.className='dino-step';steps.append(s);}updateProgress();};const refreshNav=()=>{prev.disabled=index===0;next.disabled=!task()?.completed;};
 const full=t=>t.placedLetters.every(Boolean),assembled=t=>t.placedLetters.map(x=>x?.letter||'').join('').toLowerCase();const render=()=>{const t=task();if(!t)return;buildPicture.textContent=t.picture;buildSlots.replaceChildren(...t.placedLetters.map(tile=>{const b=document.createElement('button');b.className='build-slot'+(!tile?' empty':'')+(t.completed?' success':'');if(tile)G.setLearningText(b,tile.letter);b.disabled=!tile||t.completed;if(tile)b.addEventListener('click',()=>returnLetter(tile.id));return b;}));buildLetters.replaceChildren(...t.shuffledLetters.map(tile=>{const b=document.createElement('button');b.className='build-letter';G.setLearningText(b,tile.letter);b.disabled=t.completed||t.placedLetters.some(x=>x?.id===tile.id);b.addEventListener('click',()=>place(tile.id));return b;}));refreshNav();};
 const check=()=>{const t=task();if(!t||!full(t))return;if(assembled(t)===t.targetWord.toLowerCase()){t.attempted=true;t.completed=true;const rewarded=!t.hadWrongAttempt&&!t.rewarded;if(rewarded){t.rewarded=true;t.closed=true;updateProgress();G.celebrate(buildGame);}render();}else{t.attempted=true;t.hadWrongAttempt=true;buildSlots.classList.add('try-again');refreshNav();}};const place=id=>{const t=task();if(!t||t.completed)return;const tile=t.shuffledLetters.find(x=>x.id===id),slot=t.placedLetters.findIndex(x=>x===null);if(!tile||slot<0||t.placedLetters.some(x=>x?.id===id))return;t.placedLetters[slot]=tile;render();check();};const returnLetter=id=>{const t=task();if(!t||t.completed)return;const slot=t.placedLetters.findIndex(x=>x?.id===id);if(slot>=0)t.placedLetters[slot]=null;buildSlots.classList.remove('try-again');render();};
 const hideCompletion=()=>{if(completion)completion.hidden=true;buildGame.hidden=false;},start=()=>{createSession();index=0;hideCompletion();makeProgress();render();},retry=()=>{const pending=original.filter(t=>!t.rewarded).map(reset);if(!pending.length){showCompletion();return;}session=shuffle(pending);index=0;render();};function showCompletion(){if(!allClosed())return;if(!completion){completion=document.createElement('section');completion.className='finish dino-celebration games-completion';completion.innerHTML=G.completionHtml;buildGame.insertAdjacentElement('afterend',completion);completion.querySelector('.dino-again')?.addEventListener('click',start);}buildGame.hidden=true;completion.hidden=false;}
 const module={hide:()=>{if(completion)completion.hidden=true;buildGame.hidden=true;},close:()=>{isOpen=false;module.hide();},setClosed:()=>{isOpen=false;}};G.register(module);buildCard?.addEventListener('click',()=>{isOpen=true;G.hideOtherGames(module);gamesGrid.hidden=true;if(childTabs)childTabs.hidden=true;start();});document.getElementById('buildAllGames')?.addEventListener('click',G.showGamesList);prev?.addEventListener('click',()=>{if(index>0){index--;render();}});next?.addEventListener('click',()=>{if(!task()?.completed)return;if(index<session.length-1){index++;render();}else if(allClosed())showCompletion();else retry();});buildPicture?.addEventListener('click',()=>{if(task()&&typeof speak==='function')speak(task().targetWord);});
});
