'use strict';
document.addEventListener('DOMContentLoaded',()=>{
 const G=window.PhonikaGames,{shuffle,arrangeTasks}=G,Domain=window.PhonikaGameDomain,childTabs=document.getElementById('childTabs'),gamesGrid=document.getElementById('gamesGrid');
 const buildCard=G.gameCards.find(el=>el.textContent.includes('Собери слово'));if(buildCard)buildCard.id='buildWordGameCard';const buildGame=document.createElement('div');buildGame.id='buildWordGame';buildGame.className='find-game build-word-game';buildGame.hidden=true;buildGame.innerHTML='<div class="find-header"><button id="buildAllGames" class="find-back">← Игры</button><span class="find-title">Собери слово</span></div><div class="dino-track"><div class="dino-path"></div><div id="buildDinoSteps" class="dino-steps"></div><div id="buildDino" class="dino">🦕</div><div class="dino-finish">🏁</div></div><div class="build-task-row"><button id="buildPrev" class="find-nav-arrow">‹</button><div class="build-center"><button id="buildPicture" class="find-picture build-picture"></button><div id="buildSlots" class="build-slots"></div><div id="buildLetters" class="build-letters"></div></div><button id="buildNext" class="find-nav-arrow">›</button></div>';gamesGrid?.insertAdjacentElement('afterend',buildGame);
 const buildPicture=document.getElementById('buildPicture'),buildSlots=document.getElementById('buildSlots'),buildLetters=document.getElementById('buildLetters'),steps=document.getElementById('buildDinoSteps'),dino=document.getElementById('buildDino'),prev=document.getElementById('buildPrev'),next=document.getElementById('buildNext');let isOpen=false,session=null,completion=null;
 const game=new Domain.BuildWordGame({shuffle,arrangeTasks}),pictureMap=()=>new Map(Object.values(curriculum).flat().map(([w,p])=>[w,p])),entries=()=>{const pics=pictureMap();return [...new Set(availableWords().map(([word])=>word))].map(word=>({word,picture:pics.get(word)||''}));};
 const task=()=>session?.currentTask,progress=()=>session?.rewardedCount||0,allClosed=()=>Boolean(session?.isRewardComplete);const updateProgress=()=>{const p=progress(),goal=session?.originalTasks.length||0;[...steps.children].forEach((s,i)=>{s.classList.toggle('done',i<p);s.innerHTML=i<p?'<span class="step-check">✓</span>':'';});const pct=goal?p/goal*100:0;dino.style.left=`calc(${pct}% - ${pct/100*46}px)`;};const makeProgress=()=>{steps.replaceChildren();for(let i=0;i<(session?.originalTasks.length||0);i++){const s=document.createElement('span');s.className='dino-step';steps.append(s);}updateProgress();};const refreshNav=()=>{prev.disabled=!session||session.currentIndex===0;next.disabled=!task()?.completed;};
 const render=()=>{const t=task();if(!t)return;buildPicture.textContent=t.picture;buildSlots.classList.remove('try-again');buildSlots.replaceChildren(...t.placedLetters.map(tile=>{const b=document.createElement('button');b.className='build-slot'+(!tile?' empty':'')+(t.completed?' success':'');if(tile)G.setLearningText(b,tile.letter);b.disabled=!tile||t.completed;if(tile)b.addEventListener('click',()=>returnLetter(tile.id));return b;}));buildLetters.replaceChildren(...t.shuffledLetters.map(tile=>{const b=document.createElement('button');b.className='build-letter';G.setLearningText(b,tile.letter);b.disabled=t.completed||t.placedLetters.some(x=>x?.id===tile.id);b.addEventListener('click',()=>place(tile.id));return b;}));refreshNav();};
 const place=id=>{if(!task()||task().completed)return;const result=game.placeLetter(session,id);render();if(result.type==='WRONG'){buildSlots.classList.add('try-again');refreshNav();}else if(result.type==='CORRECT'){if(result.rewarded){updateProgress();G.celebrate(buildGame);}render();}};const returnLetter=id=>{const result=game.returnLetter(session,id);if(result.type==='RETURNED')render();};
 const hideCompletion=()=>{if(completion)completion.hidden=true;buildGame.hidden=false;},start=()=>{session=game.createSession(entries(),wordSessionSize);hideCompletion();makeProgress();render();};function showCompletion(){if(!allClosed())return;if(!completion){completion=document.createElement('section');completion.className='finish dino-celebration games-completion';completion.innerHTML=G.completionHtml;buildGame.insertAdjacentElement('afterend',completion);completion.querySelector('.dino-again')?.addEventListener('click',start);}buildGame.hidden=true;completion.hidden=false;}
 const module={hide:()=>{if(completion)completion.hidden=true;buildGame.hidden=true;},close:()=>{isOpen=false;module.hide();},setClosed:()=>{isOpen=false;}};G.register(module);buildCard?.addEventListener('click',()=>{isOpen=true;G.hideOtherGames(module);gamesGrid.hidden=true;if(childTabs)childTabs.hidden=true;start();});document.getElementById('buildAllGames')?.addEventListener('click',G.showGamesList);prev?.addEventListener('click',()=>{if(session?.currentIndex>0){game.previous(session);render();}});next?.addEventListener('click',()=>{if(!task()?.completed)return;const transition=game.advance(session);if(transition.type==='COMPLETED')showCompletion();else render();});buildPicture?.addEventListener('click',()=>{if(task()&&typeof speak==='function')speak(task().targetWord);});
});
