'use strict';
document.addEventListener('DOMContentLoaded',()=>{
 const G=window.PhonikaGames,{shuffle,createDoubleExposureTasks}=G,childTabs=document.getElementById('childTabs'),gamesTab=document.getElementById('gamesTab'),gamesGrid=document.getElementById('gamesGrid');
 const catchCard=G.gameCards.find(el=>el.textContent.trim()==='Поймай');if(catchCard)catchCard.id='catchGameCard';
 const catchGame=document.createElement('div');catchGame.id='catchGame';catchGame.className='find-game catch-game';catchGame.hidden=true;catchGame.innerHTML='<div class="find-header"><button id="catchAllGames" type="button" class="find-back">← Игры</button><span class="find-title">Поймай</span></div><div class="dino-track" aria-label="Прогресс игры"><div class="dino-path"></div><div id="catchDinoSteps" class="dino-steps"></div><div id="catchDino" class="dino">🦕</div><div class="dino-finish">🏁</div></div><div class="catch-task-row"><button id="catchPrev" type="button" class="find-nav-arrow" aria-label="Предыдущее задание">‹</button><div class="catch-center"><div class="catch-prompt"><span>Поймай</span><span id="catchTarget"></span></div><div id="catchArea" class="catch-area" aria-label="Варианты ответа"></div></div><button id="catchNext" type="button" class="find-nav-arrow" aria-label="Следующее задание">›</button></div>';
 const styleEl=document.createElement('style');styleEl.textContent='.catch-game{width:min(100%,620px);margin:0 auto;text-align:center;position:relative}.catch-game .dino-track{margin:0 auto 5px}.catch-game .dino-track .dino{font-size:68px;top:-9px}.catch-task-row{display:grid;grid-template-columns:64px minmax(0,1fr) 64px;align-items:center;gap:12px;min-height:350px;width:100%}.catch-task-row>.find-nav-arrow{position:static;transform:none;justify-self:center}.catch-task-row>.find-nav-arrow:active:not(:disabled){transform:scale(.96)}.catch-center{min-width:0;width:100%;display:grid;gap:22px}.catch-prompt{display:flex;flex-direction:column;align-items:center;gap:5px;font-size:30px;font-weight:800;color:#123f73;line-height:1.15}.catch-target{display:block;font-size:clamp(44px,8vw,58px);line-height:1.15}.catch-area{position:relative;width:100%;height:220px;overflow:hidden;border-radius:20px;background:transparent}.catch-lane{position:absolute;left:0;width:100%;height:94px;overflow:visible}.catch-lane:first-child{top:8px}.catch-lane:last-child{bottom:8px}.catch-answer{position:absolute;left:0;top:7px;width:max-content;min-width:116px;max-width:calc(50% - 8px);height:76px;min-height:76px;padding:8px 24px;overflow:visible;white-space:nowrap;background:#fff;color:#123f73;border:1px solid #cbd9ea;border-radius:17px;box-shadow:0 4px 12px #123f7315;font-size:clamp(28px,5vw,36px);font-weight:800;cursor:pointer;animation:catch-glide 8s ease-in-out infinite alternate;will-change:left}.catch-lane:nth-child(2) .catch-answer{animation-direction:alternate-reverse;animation-duration:9s}.catch-answer.correct{background:#35b96f;color:#fff;border-color:#35b96f}.catch-answer.try-again{box-shadow:0 0 0 2px #cbd9ea inset}.catch-area.stopped .catch-answer{animation-play-state:paused}.catch-answer:disabled{opacity:1;cursor:default}@keyframes catch-glide{from{left:0}to{left:calc(100% - var(--catch-card-width))}}@media(prefers-reduced-motion:reduce){.catch-answer{animation:none;left:50%;transform:translateX(-50%)}}@media(max-width:430px){.catch-game .dino-track .dino{font-size:58px;top:-7px}.catch-task-row{grid-template-columns:48px minmax(0,1fr) 48px;gap:4px;min-height:300px}.catch-prompt{font-size:25px}.catch-target{font-size:40px}.catch-area{height:190px}.catch-lane{height:82px}.catch-answer{min-width:100px;max-width:calc(60% - 6px);height:68px;min-height:68px;padding-inline:18px;font-size:clamp(24px,7vw,30px)}}';document.head.appendChild(styleEl);
 const anchor=document.getElementById('missingWordGame')||document.getElementById('buildWordGame')||document.getElementById('findGame')||gamesGrid;anchor.insertAdjacentElement('afterend',catchGame);
 const catchTarget=document.getElementById('catchTarget'),catchArea=document.getElementById('catchArea'),catchDinoSteps=document.getElementById('catchDinoSteps'),catchDino=document.getElementById('catchDino'),catchPrev=document.getElementById('catchPrev'),catchNext=document.getElementById('catchNext');
 let isCatchOpen=false,catchTaskIndex=0,catchSession=[],catchCompletion=null;
 const currentWordSet=()=>[...new Set((sessionWords||[]).slice(0,wordSessionSize))];
 const createCatchSession=()=>{const words=currentWordSet(),fallback=[...new Set(Object.values(curriculum).flat().map(([word])=>word))];catchSession=createDoubleExposureTasks(words,fallback,(targetWord,distractor)=>({targetWord,distractor,answers:shuffle([targetWord,distractor]),attempted:false,completed:false,hadWrongAttempt:false,rewarded:false}));};
 const currentCatchTask=()=>catchSession[catchTaskIndex],catchProgress=()=>catchSession.filter(task=>task.rewarded).length,passedCatchTasks=()=>catchSession.filter(task=>task.attempted).length;
 const updateCatchProgress=()=>{const progress=catchProgress(),goal=catchSession.length;[...catchDinoSteps.children].forEach((step,i)=>{step.classList.toggle('done',i<progress);step.innerHTML=i<progress?'<span class="step-check">✓</span>':'';});const pct=goal?Math.min(100,(progress/goal)*100):0;catchDino.style.left=`calc(${pct}% - ${pct/100*46}px)`;};
 const buildCatchProgress=()=>{catchDinoSteps.replaceChildren();for(let i=0;i<catchSession.length;i++){const step=document.createElement('span');step.className='dino-step';catchDinoSteps.append(step);}updateCatchProgress();};
 const refreshCatchNav=()=>{const task=currentCatchTask();catchPrev.disabled=catchTaskIndex===0;catchNext.disabled=!task?.attempted||catchTaskIndex>=catchSession.length-1;};
 const finishCatchAttempt=()=>{refreshCatchNav();if(passedCatchTasks()===catchSession.length)setTimeout(showCatchCompletion,900);};
 const renderCatchTask=()=>{const task=currentCatchTask();if(!task)return;G.setLearningText(catchTarget,task.targetWord);catchTarget.classList.add('catch-target');catchArea.classList.toggle('stopped',task.completed);catchArea.replaceChildren(...task.answers.map((label,index)=>{const lane=document.createElement('div');lane.className='catch-lane';const btn=document.createElement('button');btn.type='button';btn.className='catch-answer'+(task.completed&&label===task.targetWord?' correct':'');G.setLearningText(btn,label);btn.disabled=task.completed;btn.setAttribute('aria-label',G.formatLearningText(label));btn.addEventListener('click',()=>{if(task.completed)return;const correct=label===task.targetWord;if(correct){btn.classList.add('correct');task.attempted=true;task.completed=true;task.rewarded=!task.hadWrongAttempt;catchArea.classList.add('stopped');catchArea.querySelectorAll('.catch-answer').forEach(x=>x.disabled=true);if(task.rewarded){updateCatchProgress();G.celebrate(btn);}finishCatchAttempt();}else{task.attempted=true;task.hadWrongAttempt=true;task.rewarded=false;btn.classList.add('try-again');finishCatchAttempt();}});lane.appendChild(btn);requestAnimationFrame(()=>btn.style.setProperty('--catch-card-width',`${btn.offsetWidth}px`));return lane;}));refreshCatchNav();};
 const hideCatchCompletion=()=>{if(catchCompletion)catchCompletion.hidden=true;catchGame.hidden=false;};
 const startCatchSession=()=>{createCatchSession();catchTaskIndex=0;hideCatchCompletion();buildCatchProgress();renderCatchTask();};
 function showCatchCompletion(){if(passedCatchTasks()!==catchSession.length)return;if(!catchCompletion){catchCompletion=document.createElement('section');catchCompletion.id='catchCompletion';catchCompletion.className='finish dino-celebration games-completion';catchCompletion.innerHTML=G.completionHtml;catchGame.insertAdjacentElement('afterend',catchCompletion);catchCompletion.querySelector('.dino-again')?.addEventListener('click',startCatchSession);}catchGame.hidden=true;catchCompletion.hidden=false;}
 const restoreCatchAfterParent=()=>{if(!isCatchOpen)return;['readingView','lettersView','finishView','letterFinishView'].forEach(id=>{const el=document.getElementById(id);if(el)el.hidden=true;});const gamesView=document.getElementById('gamesView');if(gamesView)gamesView.hidden=false;if(gamesGrid)gamesGrid.hidden=true;if(childTabs)childTabs.hidden=true;gamesTab?.classList.add('on');hideCatchCompletion();renderCatchTask();updateCatchProgress();};
 const module={hide:()=>{if(catchCompletion)catchCompletion.hidden=true;catchGame.hidden=true;},close:()=>{isCatchOpen=false;module.hide();},setClosed:()=>{isCatchOpen=false;}};G.register(module);
 const openCatchGame=()=>{isCatchOpen=true;G.hideOtherGames(module);gamesGrid.hidden=true;catchGame.hidden=false;if(childTabs)childTabs.hidden=true;startCatchSession();};
 catchCard?.addEventListener('click',openCatchGame);document.getElementById('catchAllGames')?.addEventListener('click',G.showGamesList);
 catchPrev?.addEventListener('click',()=>{if(catchTaskIndex>0){catchTaskIndex--;renderCatchTask();}});catchNext?.addEventListener('click',()=>{if(!catchNext.disabled&&catchTaskIndex<catchSession.length-1){catchTaskIndex++;renderCatchTask();}});
 document.getElementById('parentBack')?.addEventListener('click',restoreCatchAfterParent);
});
