'use strict';
document.addEventListener('DOMContentLoaded',()=>{
 const G=window.PhonikaGames,{shuffle,arrangeTasks}=G,Domain=window.PhonikaGameDomain,childTabs=document.getElementById('childTabs'),gamesGrid=document.getElementById('gamesGrid');
 if(!Domain?.CatchGame)throw new Error('CatchGame domain is not loaded');
 const catchDomain=new Domain.CatchGame({shuffle,arrangeTasks});
 const catchCard=G.gameCards.find(el=>el.textContent.includes('Поймай'));if(catchCard)catchCard.id='catchGameCard';
 const catchGame=document.createElement('div');catchGame.id='catchGame';catchGame.className='find-game catch-game';catchGame.hidden=true;catchGame.innerHTML='<div class="find-header"><button id="catchAllGames" type="button" class="find-back">← Игры</button><span class="find-title">Поймай</span></div><div class="dino-track"><div class="dino-path"></div><div id="catchDinoSteps" class="dino-steps"></div><div id="catchDino" class="dino">🦕</div><div class="dino-finish">🏁</div></div><div class="catch-task-row"><button id="catchPrev" type="button" class="find-nav-arrow">‹</button><div class="catch-center"><div class="catch-target-help"><button id="catchTargetPicture" type="button" class="catch-target-picture"></button></div><div id="catchArea" class="catch-area"></div></div><button id="catchNext" type="button" class="find-nav-arrow">›</button></div>';
 const styleEl=document.createElement('style');styleEl.textContent='.catch-game{width:100%;max-width:1120px;margin:auto;text-align:center}.catch-task-row{position:relative;display:flex;justify-content:center;padding:0 76px}.catch-center{width:100%;max-width:920px}.catch-target-picture{min-width:76px;height:76px;font-size:48px}.catch-area{position:relative;width:100%;height:330px;min-height:220px;overflow:hidden}.catch-answer{position:absolute;left:0;top:0;box-sizing:border-box;width:max-content;min-width:132px;max-width:calc(100% - 28px);height:auto;min-height:82px;padding:10px 26px;white-space:nowrap;overflow:visible;border-radius:17px;font-size:clamp(30px,5vw,40px);line-height:1.15;font-weight:800;transition-property:transform;transition-timing-function:ease-in-out}.catch-answer.correct{background:#35b96f;color:#fff}.catch-game .find-nav-arrow.game-nav-success{background:inherit;color:inherit;border-color:inherit;box-shadow:inherit}.catch-game .find-nav-arrow.game-nav-success:hover{background:inherit;border-color:inherit}@media(max-width:430px){.catch-answer{min-width:112px;max-width:calc(100% - 20px);min-height:70px;padding:8px 18px;font-size:clamp(28px,8vw,36px)}}';document.head.appendChild(styleEl);(document.getElementById('missingWordGame')||document.getElementById('buildWordGame')||document.getElementById('findGame')||gamesGrid).insertAdjacentElement('afterend',catchGame);
 const catchTargetPicture=document.getElementById('catchTargetPicture'),catchArea=document.getElementById('catchArea'),catchDinoSteps=document.getElementById('catchDinoSteps'),catchDino=document.getElementById('catchDino'),catchPrev=document.getElementById('catchPrev'),catchNext=document.getElementById('catchNext');let isCatchOpen=false,catchSession=null,catchCompletion=null,catchMoveToken=0,catchMoveTimers=[];
 const availableWordPool=()=>[...new Set(availableWords().map(([word])=>word))],wordData=word=>availableWords().find(([candidate])=>candidate===word),currentTask=()=>catchSession?.currentTask||null;
 const progress=()=>catchSession?.rewardedCount||0,goal=()=>catchSession?.originalTasks.length||0;
 const updateProgress=()=>{const done=progress(),total=goal();[...catchDinoSteps.children].forEach((s,i)=>{s.classList.toggle('done',i<done);s.innerHTML=i<done?'<span class="step-check">✓</span>':'';});const pct=total?Math.min(100,done/total*100):0;catchDino.style.left=`calc(${pct}% - ${pct/100*46}px)`;};
 const buildProgress=()=>{catchDinoSteps.replaceChildren();for(let i=0;i<goal();i++){const s=document.createElement('span');s.className='dino-step';catchDinoSteps.append(s);}updateProgress();};
 const refreshNav=()=>{catchPrev.disabled=!catchSession||catchSession.currentIndex===0;catchNext.disabled=!currentTask()?.completed;catchNext.classList.remove('game-nav-success');};
 const stopMovement=()=>{catchMoveToken++;catchMoveTimers.forEach(clearTimeout);catchMoveTimers=[];};const overlap=(a,b,g=22)=>!(a.x+a.w+g<=b.x||b.x+b.w+g<=a.x||a.y+a.h+g<=b.y||b.y+b.h+g<=a.y);const syncHeight=()=>{if(catchGame.hidden)return;const top=catchArea.getBoundingClientRect().top,h=window.visualViewport?.height||innerHeight;catchArea.style.height=`${Math.max(220,Math.floor(h-top-20))}px`;};
 const startMovement=()=>{stopMovement();syncHeight();const token=catchMoveToken,cards=[...catchArea.querySelectorAll('.catch-answer')];if(!cards.length||currentTask()?.completed)return;const areaW=catchArea.clientWidth,areaH=catchArea.clientHeight,pad=14,pos=[];cards.forEach((c,i)=>{const w=c.offsetWidth,h=c.offsetHeight,x=i?areaW-w-pad:pad,y=i?areaH-h-pad:pad;pos[i]={x,y,w,h};c.style.transitionDuration='0ms';c.style.transform=`translate(${x}px,${y}px)`;});requestAnimationFrame(()=>cards.forEach((card,i)=>{const move=()=>{if(token!==catchMoveToken||currentTask()?.completed)return;const p=pos[i],other=pos[1-i],maxX=Math.max(pad,catchArea.clientWidth-p.w-pad),maxY=Math.max(pad,catchArea.clientHeight-p.h-pad);let n;for(let k=0;k<14;k++){const q={x:pad+Math.random()*(maxX-pad),y:pad+Math.random()*(maxY-pad),w:p.w,h:p.h};if(!other||!overlap(q,other)){n=q;break;}}n=n||{x:i?maxX:pad,y:i?pad:maxY,w:p.w,h:p.h};const duration=Math.max(4200,Math.min(7200,3800+Math.hypot(n.x-p.x,n.y-p.y)*6+Math.random()*900));pos[i]=n;card.style.transitionDuration=`${duration}ms`;card.style.transform=`translate(${n.x}px,${n.y}px)`;catchMoveTimers.push(setTimeout(move,duration+120));};move();}));};
 const render=()=>{stopMovement();const task=currentTask();if(!task)return;catchTargetPicture.textContent=wordData(task.targetWord)?.[1]||'';catchTargetPicture.setAttribute('aria-label',`Послушать слово ${task.targetWord}`);catchArea.replaceChildren(...task.answers.map(label=>{const b=document.createElement('button');b.type='button';b.className='catch-answer'+(task.completed&&label===task.targetWord?' correct':'');G.setLearningText(b,label);b.disabled=task.completed;b.addEventListener('click',()=>{if(task.completed)return;const result=catchDomain.answer(catchSession,label);if(!result)return;if(result.attempt.correct){b.classList.add('correct');if(result.rewarded){updateProgress();G.celebrate(b);}stopMovement();catchArea.querySelectorAll('.catch-answer').forEach(x=>x.disabled=true);}else b.classList.add('try-again');refreshNav();});return b;}));refreshNav();requestAnimationFrame(startMovement);};
 const hideCompletion=()=>{if(catchCompletion)catchCompletion.hidden=true;catchGame.hidden=false;};
 const startSession=()=>{stopMovement();catchSession=catchDomain.createSession(availableWordPool(),wordSessionSize);hideCompletion();buildProgress();render();};
 function showCompletion(){stopMovement();if(!catchCompletion){catchCompletion=document.createElement('section');catchCompletion.className='finish dino-celebration games-completion';catchCompletion.innerHTML=G.completionHtml;catchGame.insertAdjacentElement('afterend',catchCompletion);catchCompletion.querySelector('.dino-again')?.addEventListener('click',startSession);}catchGame.hidden=true;catchCompletion.hidden=false;}
 const advance=()=>{const transition=catchDomain.advance(catchSession);if(transition.type==='BLOCKED')return;if(transition.type==='COMPLETED'){showCompletion();return;}render();};
 const module={hide:()=>{stopMovement();if(catchCompletion)catchCompletion.hidden=true;catchGame.hidden=true;},close:()=>{isCatchOpen=false;module.hide();},setClosed:()=>{isCatchOpen=false;stopMovement();}};G.register(module);
 catchCard?.addEventListener('click',()=>{isCatchOpen=true;G.hideOtherGames(module);gamesGrid.hidden=true;if(childTabs)childTabs.hidden=true;startSession();});document.getElementById('catchAllGames')?.addEventListener('click',G.showGamesList);catchTargetPicture?.addEventListener('click',()=>{if(currentTask()&&typeof speak==='function')speak(currentTask().targetWord);});catchPrev?.addEventListener('click',()=>{if(catchSession?.currentIndex>0){catchDomain.previous(catchSession);render();}});catchNext?.addEventListener('click',advance);window.addEventListener('resize',()=>{if(isCatchOpen&&!catchGame.hidden&&!currentTask()?.completed)startMovement();});
});
