'use strict';
document.addEventListener('DOMContentLoaded',()=>{
 const G=window.PhonikaGames,{shuffle,arrangeTasks}=G,{FindGame}=window.PhonikaGameDomain,childTabs=document.getElementById('childTabs'),gamesTab=document.getElementById('gamesTab'),gamesGrid=document.getElementById('gamesGrid'),findGame=document.getElementById('findGame');
 const findCard=document.getElementById('findGameCard'),soundsMode=document.getElementById('findSoundsMode'),wordsMode=document.getElementById('findWordsMode'),answers=document.getElementById('findAnswers'),findPicture=document.getElementById('findPicture'),allGames=document.getElementById('allGames'),findDinoSteps=document.getElementById('findDinoSteps'),findDino=document.getElementById('findDino'),findPrev=document.getElementById('findPrev'),findNext=document.getElementById('findNext');
 const syllables=['ма','мо','му','ми','ка','ко','ку','ки','са','со','су','си','та','то','ту','ти','на','но','ну','ни','ла','ло','лу','ли','ра','ро','ру','ри'];
 const canonicalSyllable=value=>String(value||'').trim().toLocaleLowerCase('ru-RU');
 const domain=new FindGame({shuffle,arrangeTasks});
 let findCompletion=null,isFindOpen=false,findMode='syllables',wordSession=null,syllableSession=null;
 const hideFindCompletion=()=>{if(findCompletion)findCompletion.hidden=true;if(findGame)findGame.hidden=false;};
 const availableWordEntries=()=>availableWords().map(([word,picture])=>({word,picture}));
 const findSession=()=>findMode==='words'?wordSession:syllableSession,currentFindTask=()=>findSession()?.currentTask||null,findGoal=()=>findSession()?.originalTasks.length||0,currentProgress=()=>findSession()?.rewardedCount||0;
 const updateFindProgress=()=>{const progress=currentProgress(),goal=findGoal();[...findDinoSteps.children].forEach((step,i)=>{const done=i<progress;step.classList.toggle('done',done);step.innerHTML=done?'<span class="step-check">✓</span>':'';});const pct=goal?Math.min(100,(progress/goal)*100):0;findDino.style.left=`calc(${pct}% - ${pct/100*46}px)`;};
 const buildFindProgress=()=>{findDinoSteps.replaceChildren();for(let i=0;i<findGoal();i++){const step=document.createElement('span');step.className='dino-step';findDinoSteps.append(step);}updateFindProgress();};
 const refreshFindNav=()=>{const session=findSession();findPrev.disabled=!session||session.currentIndex===0;findNext.disabled=!currentFindTask()?.completed;};
 const allFindClosed=()=>findSession()?.isRewardComplete===true;
 const showFindCompletion=()=>{if(!allFindClosed())return;if(!findCompletion){findCompletion=document.createElement('section');findCompletion.className='finish dino-celebration games-completion';findCompletion.innerHTML=G.completionHtml;findGame.insertAdjacentElement('afterend',findCompletion);findCompletion.querySelector('.dino-again')?.addEventListener('click',startFindSession);}findGame.hidden=true;findCompletion.hidden=false;};
 const goNextFindTask=()=>{const session=findSession();if(!session)return;const result=domain.advance(session);if(result.type==='NEXT'||result.type==='RETRY')renderFindTask();else if(result.type==='COMPLETED')showFindCompletion();};
 const renderFindTask=()=>{const task=currentFindTask();if(!task)return;const isWords=task.mode==='words',target=task.target;findPicture.textContent=isWords?task.picture:'🔊';findPicture.setAttribute('aria-label',isWords?`Послушать слово ${target}`:'Послушать слог');const questionSpans=findGame.querySelectorAll('.find-question > span');questionSpans.forEach(span=>span.hidden=!isWords);answers.replaceChildren(...task.answers.map(label=>{const correct=label===target,btn=document.createElement('button');btn.type='button';btn.className='find-answer'+(task.completed&&correct?' correct':'');G.setLearningText(btn,label);btn.addEventListener('click',()=>{if(task.completed)return;const result=domain.answer(findSession(),label);if(!result)return;if(result.attempt.correct){answers.querySelectorAll('.find-answer').forEach(x=>x.classList.remove('try-again'));btn.classList.add('correct');if(result.rewarded){updateFindProgress();G.celebrate(btn);}refreshFindNav();}else{btn.classList.add('try-again');refreshFindNav();}});return btn;}));refreshFindNav();};
 const createWordFindSession=()=>{wordSession=domain.createWordSession(availableWordEntries(),wordSessionSize);};
 const createSyllableFindSession=()=>{syllableSession=domain.createSyllableSession(syllables,wordSessionSize);};
 const startFindSession=()=>{findMode==='words'?createWordFindSession():createSyllableFindSession();hideFindCompletion();buildFindProgress();renderFindTask();};
 const setFindMode=mode=>{findMode=mode;hideFindCompletion();soundsMode.classList.toggle('active',mode==='syllables');wordsMode.classList.toggle('active',mode==='words');if(mode==='words'&&!wordSession)createWordFindSession();if(mode==='syllables'&&!syllableSession)createSyllableFindSession();buildFindProgress();renderFindTask();};
 const restoreFindAfterParent=()=>{if(!isFindOpen)return;['readingView','lettersView','finishView','letterFinishView'].forEach(id=>{const el=document.getElementById(id);if(el)el.hidden=true;});const gamesView=document.getElementById('gamesView');if(gamesView)gamesView.hidden=false;if(gamesGrid)gamesGrid.hidden=true;if(childTabs)childTabs.hidden=true;gamesTab?.classList.add('on');const session=findSession(),eligible=[...new Set(availableWordEntries().map(item=>item.word))],targetCount=Math.min(eligible.length,Math.max(1,Number(wordSessionSize)||5)),currentTargets=session?[...new Set(session.originalTasks.map(task=>task.targetWord).filter(Boolean))]:[],sessionChanged=findMode==='words'?(!session||currentTargets.length!==targetCount||currentTargets.some(word=>!eligible.includes(word))):(!session||[...new Set(session.originalTasks.map(task=>task.targetSyllable))].length!==Math.min(syllables.length,Math.max(1,Number(wordSessionSize)||5)));if(sessionChanged)startFindSession();else{hideFindCompletion();renderFindTask();updateFindProgress();}};
 const module={hide:()=>{if(findCompletion)findCompletion.hidden=true;if(findGame)findGame.hidden=true;},close:()=>{isFindOpen=false;module.hide();},setClosed:()=>{isFindOpen=false;}};G.register(module);
 if(soundsMode){soundsMode.textContent='Слоги';soundsMode.setAttribute('aria-label','Слоги');}
 findCard?.addEventListener('click',()=>{isFindOpen=true;G.hideOtherGames(module);gamesGrid.hidden=true;findGame.hidden=false;if(childTabs)childTabs.hidden=true;createWordFindSession();createSyllableFindSession();setFindMode(findMode);});
 allGames?.addEventListener('click',G.showGamesList);soundsMode?.addEventListener('click',()=>setFindMode('syllables'));wordsMode?.addEventListener('click',()=>setFindMode('words'));document.getElementById('parentBack')?.addEventListener('click',restoreFindAfterParent);findPrev?.addEventListener('click',()=>{if(domain.previous(findSession()))renderFindTask();});findNext?.addEventListener('click',goNextFindTask);findPicture?.addEventListener('click',()=>{const task=currentFindTask();if(!task)return;if(findMode==='syllables'){const target=canonicalSyllable(task.targetSyllable),spoken=target,calls=1;console.log('[Find syllable TTS]',{target,spoken,calls});if(typeof speak==='function')speak(spoken);return;}if(typeof speak==='function')speak(task.targetWord);});
});
