'use strict';
document.addEventListener('DOMContentLoaded',()=>{
 const G=window.PhonikaGames,{shuffle,arrangeTasks}=G,{MissingWordGame}=window.PhonikaGameDomain,childTabs=document.getElementById('childTabs'),gamesGrid=document.getElementById('gamesGrid');const card=G.gameCards.find(el=>el.textContent.includes('Что пропало?'));if(card)card.id='missingWordGameCard';
 const game=document.createElement('div');game.id='missingWordGame';game.className='find-game missing-word-game';game.hidden=true;game.innerHTML='<div class="find-header"><button id="missingAllGames" class="find-back">← Игры</button><span class="find-title">Что пропало?</span></div><div class="dino-track"><div class="dino-path"></div><div id="missingDinoSteps" class="dino-steps"></div><div id="missingDino" class="dino">🦕</div><div class="dino-finish">🏁</div></div><div class="missing-task-row"><button id="missingPrev" class="find-nav-arrow">‹</button><div class="missing-center"><div id="missingPrompt">Запомни</div><div class="missing-words"><div id="missingFirst" class="missing-word"></div><div id="missingSecond" class="missing-word"></div></div><div id="missingQuestion"></div><div id="missingAnswers" class="missing-answers"></div></div><button id="missingNext" class="find-nav-arrow">›</button></div>'; (document.getElementById('buildWordGame')||gamesGrid).insertAdjacentElement('afterend',game);
 const first=document.getElementById('missingFirst'),second=document.getElementById('missingSecond'),prompt=document.getElementById('missingPrompt'),question=document.getElementById('missingQuestion'),answers=document.getElementById('missingAnswers'),steps=document.getElementById('missingDinoSteps'),dino=document.getElementById('missingDino'),prev=document.getElementById('missingPrev'),next=document.getElementById('missingNext');let completion=null,timer=0,session=null;const domain=new MissingWordGame({shuffle,arrangeTasks});
 const seconds=()=>[5,7,10,15].includes(Number(saved.profile?.missingMemorySeconds))?Number(saved.profile.missingMemorySeconds):10;
 const task=()=>session?.currentTask||null,progress=()=>session?.rewardedCount||0,allClosed=()=>Boolean(session?.isRewardComplete);const updateProgress=()=>{const p=progress(),goal=session?.originalTasks.length||0;[...steps.children].forEach((s,i)=>{s.classList.toggle('done',i<p);s.innerHTML=i<p?'<span class="step-check">✓</span>':'';});const pct=goal?p/goal*100:0;dino.style.left=`calc(${pct}% - ${pct/100*46}px)`;};const makeProgress=()=>{steps.replaceChildren();for(let i=0;i<(session?.originalTasks.length||0);i++){const s=document.createElement('span');s.className='dino-step';steps.append(s);}updateProgress();};const refreshNav=()=>{prev.disabled=!session||session.currentIndex===0;next.disabled=!task()?.completed;};
 const reveal=()=>{if(session&&domain.reveal(session))render();};const render=()=>{clearTimeout(timer);const t=task();if(!t)return;const answering=t.phase==='answer';prompt.textContent=answering?'':'Запомни';const hide=answering&&!t.completed;if(hide&&t.firstWord===t.missingWord)first.textContent='?';else G.setLearningText(first,t.firstWord);if(hide&&t.secondWord===t.missingWord)second.textContent='?';else G.setLearningText(second,t.secondWord);question.textContent=answering?'Что пропало?':'';answers.replaceChildren();if(answering)t.answers.forEach(label=>{const b=document.createElement('button');b.className='missing-answer'+(t.completed&&label===t.missingWord?' correct':'');G.setLearningText(b,label);b.disabled=t.completed;b.addEventListener('click',()=>{const result=domain.answer(session,label);if(!result)return;if(result.attempt.correct){b.classList.add('correct');if(result.rewarded){updateProgress();G.celebrate(b);}G.setLearningText(first,t.firstWord);G.setLearningText(second,t.secondWord);}else b.classList.add('try-again');refreshNav();});answers.append(b);});refreshNav();if(!answering)timer=setTimeout(reveal,seconds()*1000);};
 const start=()=>{clearTimeout(timer);const pool=[...new Set(availableWords().map(([word])=>word))];session=domain.createSession(pool,wordSessionSize);if(completion)completion.hidden=true;game.hidden=false;makeProgress();render();};function showCompletion(){if(!allClosed())return;if(!completion){completion=document.createElement('section');completion.className='finish dino-celebration games-completion';completion.innerHTML=G.completionHtml;game.insertAdjacentElement('afterend',completion);completion.querySelector('.dino-again')?.addEventListener('click',start);}game.hidden=true;completion.hidden=false;}
 const module={hide:()=>{clearTimeout(timer);if(completion)completion.hidden=true;game.hidden=true;},close:()=>module.hide()};G.register(module);card?.addEventListener('click',()=>{G.hideOtherGames(module);gamesGrid.hidden=true;if(childTabs)childTabs.hidden=true;start();});document.getElementById('missingAllGames')?.addEventListener('click',G.showGamesList);prev?.addEventListener('click',()=>{if(session&&domain.previous(session))render();});next?.addEventListener('click',()=>{if(!session)return;const result=domain.advance(session);if(result.type==='NEXT'||result.type==='RETRY')render();else if(result.type==='COMPLETED')showCompletion();});
});
