'use strict';
document.addEventListener('DOMContentLoaded',()=>{
 const G=window.PhonikaGames,{shuffle,arrangeTasks}=G,childTabs=document.getElementById('childTabs'),gamesGrid=document.getElementById('gamesGrid');const card=G.gameCards.find(el=>el.textContent.includes('Что пропало?'));if(card)card.id='missingWordGameCard';
 const game=document.createElement('div');game.id='missingWordGame';game.className='find-game missing-word-game';game.hidden=true;game.innerHTML='<div class="find-header"><button id="missingAllGames" class="find-back">← Игры</button><span class="find-title">Что пропало?</span></div><div class="dino-track"><div class="dino-path"></div><div id="missingDinoSteps" class="dino-steps"></div><div id="missingDino" class="dino">🦕</div><div class="dino-finish">🏁</div></div><div class="missing-task-row"><button id="missingPrev" class="find-nav-arrow">‹</button><div class="missing-center"><div id="missingPrompt">Запомни</div><div class="missing-words"><div id="missingFirst" class="missing-word"></div><div id="missingSecond" class="missing-word"></div></div><div id="missingQuestion"></div><div id="missingAnswers" class="missing-answers"></div></div><button id="missingNext" class="find-nav-arrow">›</button></div>'; (document.getElementById('buildWordGame')||gamesGrid).insertAdjacentElement('afterend',game);
 const first=document.getElementById('missingFirst'),second=document.getElementById('missingSecond'),prompt=document.getElementById('missingPrompt'),question=document.getElementById('missingQuestion'),answers=document.getElementById('missingAnswers'),steps=document.getElementById('missingDinoSteps'),dino=document.getElementById('missingDino'),prev=document.getElementById('missingPrev'),next=document.getElementById('missingNext');let index=0,session=[],original=[],completion=null,timer=0;
 const seconds=()=>[5,7,10,15].includes(Number(saved.profile?.missingMemorySeconds))?Number(saved.profile.missingMemorySeconds):10;
 const createSession=()=>{const words=[...new Set((sessionWords||[]).slice(0,wordSessionSize))],tasks=[];words.forEach(target=>{for(let e=0;e<2;e++){const remaining=shuffle(words.filter(w=>w!==target))[0],distractor=shuffle(words.filter(w=>w!==target&&w!==remaining))[0]||remaining,hideFirst=Math.random()<.5;tasks.push({targetWord:target,firstWord:hideFirst?target:remaining,secondWord:hideFirst?remaining:target,missingWord:target,distractor,answers:shuffle([target,distractor]),attempted:false,completed:false,hadWrongAttempt:false,rewarded:false,closed:false,phase:'memorize'});}});original=arrangeTasks(tasks);session=[...original];};
 const reset=t=>{t.attempted=false;t.completed=false;t.hadWrongAttempt=false;t.phase='memorize';return t;},task=()=>session[index],progress=()=>original.filter(t=>t.rewarded).length,allClosed=()=>original.length>0&&progress()===original.length;const updateProgress=()=>{const p=progress(),goal=original.length;[...steps.children].forEach((s,i)=>{s.classList.toggle('done',i<p);s.innerHTML=i<p?'<span class="step-check">✓</span>':'';});const pct=goal?p/goal*100:0;dino.style.left=`calc(${pct}% - ${pct/100*46}px)`;};const makeProgress=()=>{steps.replaceChildren();for(let i=0;i<original.length;i++){const s=document.createElement('span');s.className='dino-step';steps.append(s);}updateProgress();};const refreshNav=()=>{prev.disabled=index===0;next.disabled=!task()?.completed;};
 const reveal=()=>{const t=task();if(t){t.phase='answer';render();}};const render=()=>{clearTimeout(timer);const t=task();if(!t)return;const answering=t.phase==='answer';prompt.textContent=answering?'':'Запомни';const hide=answering&&!t.completed;if(hide&&t.firstWord===t.missingWord)first.textContent='?';else G.setLearningText(first,t.firstWord);if(hide&&t.secondWord===t.missingWord)second.textContent='?';else G.setLearningText(second,t.secondWord);question.textContent=answering?'Что пропало?':'';answers.replaceChildren();if(answering)t.answers.forEach(label=>{const b=document.createElement('button');b.className='missing-answer'+(t.completed&&label===t.missingWord?' correct':'');G.setLearningText(b,label);b.disabled=t.completed;b.addEventListener('click',()=>{if(t.completed)return;if(label===t.missingWord){b.classList.add('correct');t.attempted=true;t.completed=true;const rewarded=!t.hadWrongAttempt&&!t.rewarded;if(rewarded){t.rewarded=true;t.closed=true;updateProgress();G.celebrate(b);}G.setLearningText(first,t.firstWord);G.setLearningText(second,t.secondWord);refreshNav();}else{t.attempted=true;t.hadWrongAttempt=true;b.classList.add('try-again');refreshNav();}});answers.append(b);});refreshNav();if(!answering)timer=setTimeout(reveal,seconds()*1000);};
 const start=()=>{clearTimeout(timer);createSession();index=0;if(completion)completion.hidden=true;game.hidden=false;makeProgress();render();},retry=()=>{const pending=original.filter(t=>!t.rewarded).map(reset);if(!pending.length){showCompletion();return;}session=shuffle(pending);index=0;render();};function showCompletion(){if(!allClosed())return;if(!completion){completion=document.createElement('section');completion.className='finish dino-celebration games-completion';completion.innerHTML=G.completionHtml;game.insertAdjacentElement('afterend',completion);completion.querySelector('.dino-again')?.addEventListener('click',start);}game.hidden=true;completion.hidden=false;}
 const module={hide:()=>{clearTimeout(timer);if(completion)completion.hidden=true;game.hidden=true;},close:()=>module.hide()};G.register(module);card?.addEventListener('click',()=>{G.hideOtherGames(module);gamesGrid.hidden=true;if(childTabs)childTabs.hidden=true;start();});document.getElementById('missingAllGames')?.addEventListener('click',G.showGamesList);prev?.addEventListener('click',()=>{if(index>0){index--;render();}});next?.addEventListener('click',()=>{if(!task()?.completed)return;if(index<session.length-1){index++;render();}else if(allClosed())showCompletion();else retry();});
});
