'use strict';
const $=id=>document.getElementById(id);
const curriculum={
1:[['кот','🐱'],['мак','🌺'],['сок','🧃'],['сом','🐟'],['ток','⚡'],['том','📘'],['там','👉'],['сам','🙋'],['так','👍']],
2:[['кит','🐋'],['нос','👃'],['сон','😴'],['суп','🍲'],['сук','🌿'],['ум','🧠']],
3:[['рак','🦞'],['рот','👄'],['лук','🧅'],['рис','🍚'],['мир','🌍'],['пир','🎉'],['пар','💨'],['пол','🏠']],
4:[['дом','🏠'],['дуб','🌳'],['сад','🌳'],['вид','👀'],['вал','🌊'],['два','2️⃣']],
5:[['жук','🪲'],['газ','🔥'],['зал','🏛️'],['низ','⬇️'],['нож','🔪']],
6:[['шар','🎈'],['ухо','👂'],['мех','🧥'],['хор','🎶']],
7:[['сыр','🧀'],['бык','🐂'],['дым','💨'],['май','🌷'],['мой','🧼'],['рой','🐝']],
8:[['яма','🕳️'],['ёж','🦔'],['лес','🌲'],['мел','🖍️'],['лёд','🧊'],['мяч','⚽'],['ряд','👥']],
9:[['конь','🐴'],['соль','🧂'],['ноль','0️⃣'],['тень','👤'],['пень','🪵'],['моль','🦋'],['день','☀️'],['гусь','🪿'],['рысь','🐈']],
10:[['щука','🐟'],['плащ','🧥'],['клещ','🕷️'],['ящик','📦'],['съел','🍽️']]
};
const letters=[['а','автобус','🚌'],['о','облако','☁️'],['м','мама','👩'],['с','сок','🧃'],['к','кот','🐱'],['т','торт','🎂'],['и','игрушки','🧸'],['н','нос','👃'],['у','утка','🦆'],['л','лук','🧅'],['р','рак','🦞'],['п','папа','👨'],['б','барабан','🥁'],['в','волк','🐺'],['д','дом','🏠'],['г','гусеница','🐛'],['з','зебра','🦓'],['ж','жук','🪲'],['ш','шар','🎈'],['ф','флаг','🚩'],['х','хлеб','🍞'],['ч','чайник','🫖'],['ц','цыплёнок','🐥'],['ы','сыр','🧀'],['э','эхо','📣'],['й','йог','🧘'],['е','енот','🦝'],['ё','ёжик','🦔'],['ю','юла','🌀'],['я','яма','🕳️'],['ь','конь','🐴'],['щ','щука','🐟'],['ъ','подъезд','🏢']];
const vowels='аеёиоуыэюя';const isSign=ch=>ch==='ь'||ch==='ъ';
const Storage={key:'soundsteps-profile-v1',load(){try{return JSON.parse(localStorage.getItem(this.key)||'null')}catch{return null}},save(data){localStorage.setItem(this.key,JSON.stringify({...data,updatedAt:new Date().toISOString()}));}};
const legacyLevel=Number(localStorage.getItem('ss-curriculum-level')||1);const saved=Storage.load()||{version:1,profile:{id:'local-child',name:''},level:Math.min(10,Math.max(1,legacyLevel)),style:localStorage.getItem('ss-style')||'upper',section:localStorage.getItem('ss-section')||'words',sounds:JSON.parse(localStorage.getItem('ss-letter-progress-v2')||'{}'),words:JSON.parse(localStorage.getItem('ss-progress-v2')||'{}'),soundQueue:JSON.parse(localStorage.getItem('ss-letter-queue-v2')||'[]'),wordQueue:JSON.parse(localStorage.getItem('ss-adaptive-queue')||'[]'),soundRound:1};
let level=saved.level||1,style=saved.style||'upper',section=saved.section||'words',progress=saved.words||{},letterProgress=saved.sounds||{};if(style==='hand')style='handLower';let wordQueueState=saved.wordQueue||[],soundQueueState=saved.soundQueue||[],soundRound=Math.max(1,+saved.soundRound||1),wordSessionSize=[3,5,7,10].includes(+saved.wordSessionSize)?+saved.wordSessionSize:5,letterSessionSize=[3,5,7,10].includes(+saved.letterSessionSize)?+saved.letterSessionSize:5;
let current=null,usedHint=false,markedThisTurn=false,sessionWords=[],sessionIndex=0,letterSession=[],letterIndex=0,letterMarked=false;
function persist(){Storage.save({version:3,profile:saved.profile||{id:'local-child',name:''},level,style,section,sounds:letterProgress,words:progress,soundQueue:soundQueueState,wordQueue:wordQueueState,soundRound,wordSessionSize,letterSessionSize});}
function st(w){const x=progress[w]||{};return{self:+(x.self||0),mastered:!!x.mastered,masteredAt:+(x.masteredAt||0)};}function lst(ch){const x=letterProgress[ch]||{};return{self:+(x.self||0),mastered:!!x.mastered,masteredAt:+(x.masteredAt||0),dueRound:+(x.dueRound||0),lastSeenRound:+(x.lastSeenRound||0)};}
function needed(w){return [...new Set([...w].filter(ch=>/\p{L}/u.test(ch)))];}function wordUnlocked(w){return needed(w).every(ch=>lst(ch).mastered);}function levelWords(){let a=[];for(let n=1;n<=level;n++)a.push(...(curriculum[n]||[]));return a;}function availableWords(){return levelWords().filter(x=>wordUnlocked(x[0]));}function practiceWords(){return (curriculum[level]||curriculum[1]||[]).filter(([w])=>wordUnlocked(w));}
function shuffled(items){const a=[...items];for(let i=a.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[a[i],a[j]]=[a[j],a[i]];}return a;}
function queue(){const available=practiceWords().map(x=>x[0]);if(!available.length){wordQueueState=[];persist();return [];}const previous=new Set(wordQueueState.filter(w=>available.includes(w)));const learning=available.filter(w=>!st(w).mastered);const primary=learning.length?learning:available;let candidates=shuffled(primary.filter(w=>!previous.has(w))).concat(shuffled(primary.filter(w=>previous.has(w))));if(candidates.length<wordSessionSize){const extras=shuffled(available.filter(w=>!candidates.includes(w)&&!previous.has(w))).concat(shuffled(available.filter(w=>!candidates.includes(w)&&previous.has(w))));candidates=candidates.concat(extras);}const next=candidates.slice(0,wordSessionSize);wordQueueState=next;persist();return next;}
/* Sounds: five cards per micro-session. Keep at most three from the previous set, add fresh material, retire a sound after two successes, then bring it back two sessions later for the third spaced check. */
function letterQueue(){const all=letters.map(x=>x[0]),previous=soundQueueState.filter(ch=>all.includes(ch)),q=[];const add=ch=>{if(ch&&!q.includes(ch)&&q.length<wordSessionSize)q.push(ch);};
  all.filter(ch=>{const s=lst(ch);return !s.mastered&&s.self===2&&s.dueRound>0&&s.dueRound<=soundRound;}).sort((a,b)=>lst(a).dueRound-lst(b).dueRound).forEach(add);
  previous.filter(ch=>{const s=lst(ch);return !s.mastered&&s.self<2;}).slice(0,Math.max(1,letterSessionSize-2)).forEach(add);
  all.filter(ch=>!previous.includes(ch)&&!lst(ch).mastered&&lst(ch).self===0).forEach(add);
  all.filter(ch=>!previous.includes(ch)&&!lst(ch).mastered&&lst(ch).self===1).sort((a,b)=>lst(a).lastSeenRound-lst(b).lastSeenRound).forEach(add);
  previous.filter(ch=>!lst(ch).mastered&&lst(ch).self<2).forEach(add);
  all.filter(ch=>!lst(ch).mastered&&lst(ch).self===2).sort((a,b)=>lst(a).dueRound-lst(b).dueRound).forEach(add);
  if(!q.length)all.filter(ch=>!lst(ch).mastered).forEach(add);soundQueueState=q;persist();return q;}
function shown(w){const x=w.toLowerCase();if(style==='upper'||style==='handUpper')return x.toUpperCase();if(style==='title'||style==='handTitle')return x[0].toUpperCase()+x.slice(1);return x;}function render(w,target=$('word')){target.replaceChildren(...[...shown(w)].map(ch=>{const s=document.createElement('span');s.textContent=ch;s.className=isSign(ch.toLowerCase())?'sign':vowels.includes(ch.toLowerCase())?'vowel':'consonant';return s;}));target.classList.toggle('hand',style.startsWith('hand'));}function renderLetter(ch){const el=$('letterCard');el.textContent=shown(ch);el.className='letter-card '+(isSign(ch)?'sign':vowels.includes(ch)?'vowel':'consonant')+(style.startsWith('hand')?' hand':'');}function speak(text,rate=.72){if(!('speechSynthesis'in window))return;speechSynthesis.cancel();const u=new SpeechSynthesisUtterance(text);u.lang='ru-RU';u.rate=rate;speechSynthesis.speak(u);}
function resetTurn(){usedHint=false;markedThisTurn=false;$('readOk').disabled=false;$('readOk').classList.remove('done');$('confirmation').classList.remove('show');}function showSessionWord(){current=practiceWords().find(x=>x[0]===sessionWords[sessionIndex])||levelWords().find(x=>x[0]===sessionWords[sessionIndex]);if(!current)return;render(current[0]);$('pic').textContent=current[1];$('pic').hidden=true;$('reward').textContent='';resetTurn();}function startSession(){sessionWords=queue().slice(0,wordSessionSize);sessionIndex=0;$('finishView').hidden=true;if(section==='words'){$('readingView').hidden=false;if(sessionWords.length)showSessionWord();else{$('word').textContent='';$('reward').textContent='Попробуем первые слова вместе';}}}function finishSession(){$('readingView').hidden=true;$('finishView').hidden=false;}function markIndependent(){if(!current||usedHint||markedThisTurn)return;const s=st(current[0]),was=s.mastered;s.self=Math.min(3,s.self+1);s.mastered=s.self>=3;if(s.mastered&&!was)s.masteredAt=Date.now();progress[current[0]]=s;persist();markedThisTurn=true;$('readOk').disabled=true;$('readOk').classList.add('done');$('confirmation').textContent=!was&&s.mastered?'Слово освоено':'Засчитано';$('confirmation').classList.add('show');}
function currentLetter(){return letters.find(x=>x[0]===letterSession[letterIndex])||letters[0];}function showLetter(){const x=currentLetter();renderLetter(x[0]);$('letterPicture').textContent=x[2];$('letterPicture').hidden=true;letterMarked=false;$('letterKnown').disabled=false;$('letterKnown').classList.remove('done');$('letterKnown').setAttribute('aria-label','Прочитал сам');}function startLetterSession(){letterSession=letterQueue().slice(0,letterSessionSize);letterIndex=0;$('letterFinishView').hidden=true;if(section==='letters'){$('lettersView').hidden=false;if(letterSession.length)showLetter();}}
function markLetter(){if(letterMarked)return;const ch=currentLetter()[0],s=lst(ch),was=s.mastered;s.self=Math.min(3,s.self+1);s.lastSeenRound=soundRound;if(s.self===2&&!was)s.dueRound=soundRound+2;s.mastered=s.self>=3;if(s.mastered&&!was){s.masteredAt=Date.now();s.dueRound=0;}letterProgress[ch]=s;persist();letterMarked=true;$('letterKnown').disabled=true;$('letterKnown').classList.add('done');}
function syncSessionSelectors(){if($('wordSessionSize'))$('wordSessionSize').value=String(wordSessionSize);if($('letterSessionSize'))$('letterSessionSize').value=String(letterSessionSize);}function switchSection(s){section=s;persist();$('readingView').hidden=$('lettersView').hidden=$('finishView').hidden=$('letterFinishView').hidden=true;$('wordsTab').classList.toggle('on',s==='words');$('lettersTab').classList.toggle('on',s==='letters');s==='words'?startSession():startLetterSession();}
$('help').onclick=()=>{if(current){usedHint=true;$('readOk').disabled=true;speak(current[0],.68);}};$('showPicture').onclick=()=>{if(current){usedHint=true;$('readOk').disabled=true;$('pic').hidden=false;}};$('readOk').onclick=markIndependent;$('continue').onclick=startSession;$('letterKnown').onclick=markLetter;$('letterShowPicture').onclick=()=>{$('letterPicture').hidden=false;};$('letterPicture').onclick=()=>speak(currentLetter()[1]);$('letterContinue').onclick=()=>{soundRound++;persist();startLetterSession();};$('lettersTab').onclick=()=>switchSection('letters');$('wordsTab').onclick=()=>switchSection('words');
const renderKnownSounds=()=>{const box=$('knownSounds');if(!box)return;box.innerHTML=letters.map(([ch])=>{const selected=lst(ch).mastered;const kind=isSign(ch)?'sign-choice':vowels.includes(ch)?'vowel-choice':'consonant-choice';return `<button type="button" class="known-letter ${kind}${selected?' selected':''}" data-sound="${ch}" aria-pressed="${selected}">${ch.toUpperCase()}</button>`;}).join('');box.querySelectorAll('.known-letter').forEach(btn=>btn.onclick=()=>{const ch=btn.dataset.sound,s=lst(ch);if(s.mastered){letterProgress[ch]={self:0,mastered:false,masteredAt:0,dueRound:0,lastSeenRound:0};}else{letterProgress[ch]={...s,self:3,mastered:true,masteredAt:Date.now(),dueRound:0};}soundQueueState=[];wordQueueState=[];persist();renderKnownSounds();updateKnownToggle();});};
const updateKnownToggle=()=>{const b=$('toggleAllSounds');if(!b)return;const all=letters.every(([ch])=>lst(ch).mastered);b.textContent=all?'Снять все':'Отметить все';};
const toggleAllKnown=()=>{const all=letters.every(([ch])=>lst(ch).mastered);letters.forEach(([ch])=>{const s=lst(ch);letterProgress[ch]=all?{self:0,mastered:false,masteredAt:0,dueRound:0,lastSeenRound:0}:{...s,self:3,mastered:true,masteredAt:s.masteredAt||Date.now(),dueRound:0};});soundQueueState=[];wordQueueState=[];persist();renderKnownSounds();updateKnownToggle();};
const styleLabels={normal:'абв',title:'Абв',upper:'АБВ',handLower:'абв',handTitle:'Абв',handUpper:'АБВ'};function styleRender(){$('styleSelect').textContent=styleLabels[style]||'абв';$('styleSelect').classList.toggle('hand-preview',style.startsWith('hand'));document.querySelectorAll('.style-option').forEach(b=>b.classList.toggle('selected',b.dataset.style===style));}function parentRender(){renderKnownSounds();updateKnownToggle();const q=(sessionWords&&sessionWords.length?sessionWords:queue());$('queue').innerHTML=q.length?q.map(w=>`<div class="word-row"><strong>${w}</strong><span class="status">${st(w).mastered?'3/3 · Освоено':st(w).self+'/3'}</span></div>`).join(''):'<div class="empty">Слова откроются после освоения нужных звуков.</div>';$('mastered').innerHTML=Object.keys(progress).filter(w=>st(w).mastered).map(w=>`<div class="word-row mastered-row"><strong>${w}</strong><span class="status">✓ Освоено</span></div>`).join('')||'<div class="empty">Пока нет освоенных слов.</div>';const lq=letterQueue();$('letterQueue').innerHTML=lq.map(ch=>{const s=lst(ch),label=s.self===2?'Контроль позже':s.self+'/3';return `<div class="word-row"><strong>${ch.toUpperCase()}</strong><span class="status">${s.mastered?'Освоено':label}</span></div>`;}).join('');$('masteredLetters').innerHTML=letters.map(x=>x[0]).filter(ch=>lst(ch).mastered).map(ch=>`<div class="word-row mastered-row"><strong>${ch.toUpperCase()}</strong><span class="status">✓ Освоено</span></div>`).join('')||'<div class="empty">Пока нет освоенных звуков.</div>';$('level').value=String(level);styleRender();}
$('wordSessionSize').onchange=e=>{wordSessionSize=[3,5,7,10].includes(+e.target.value)?+e.target.value:5;wordQueueState=[];persist();startSession();parentRender();};
$('letterSessionSize').onchange=e=>{letterSessionSize=[3,5,7,10].includes(+e.target.value)?+e.target.value:5;soundQueueState=[];persist();startLetterSession();parentRender();};
syncSessionSelectors();$('toggleAllSounds').onclick=toggleAllKnown;
$('parentOpen').onclick=()=>{$('childView').hidden=true;$('parentView').hidden=false;syncSessionSelectors();parentRender();};$('parentBack').onclick=()=>{$('parentView').hidden=true;$('childView').hidden=false;switchSection(section);};$('styleSelect').onclick=()=>{$('styleMenu').hidden=!$('styleMenu').hidden;};document.querySelectorAll('.style-option').forEach(b=>b.onclick=()=>{style=b.dataset.style;persist();styleRender();$('styleMenu').hidden=true;});$('level').innerHTML=Object.keys(curriculum).map(n=>`<option value="${n}">Level ${n}</option>`).join('');$('level').onchange=e=>{level=+e.target.value;wordQueueState=[];persist();startSession();parentRender();};switchSection(section==='letters'?'letters':'words');